"""Holdout v2 - reports that must NOT compile (authored after the v1 failure analysis).

New this time: corrections that contradict an earlier number, ranges, equality, rates, a hypothetical decision NOT to
alert, hedged units, and qualifiers phrased differently from v1. Same rule as v1: refusing (needs_review or rejected)
is the correct outcome for every entry here.
"""

NOCOMPILE = [
    # ---- unsupported behaviours / fields
    dict(id="HO2-U-01", style="ticket", reasonClass="unsupported-behaviour",
         text="Alert when one workstation launches cmd.exe from a Word process more than 3 times within 10 minutes. Source: endpoint process-creation events."),
    dict(id="HO2-U-02", style="email", reasonClass="unsupported-behaviour",
         text="Can we detect a single account downloading 40 or more files from the document store within 15 minutes? The proxy log has the file names."),
    dict(id="HO2-U-03", style="runbook-step", reasonClass="unsupported-behaviour",
         text="Trigger: any user is added to a privileged directory group outside a change window. Data: directory audit events (group name, target user)."),
    dict(id="HO2-U-04", style="chat-shorthand", reasonClass="unsupported-behaviour",
         text="alert when a host makes 200+ DNS queries to one domain inside 5 min - tunnelling. dns log has query name"),
    dict(id="HO2-U-05", style="jira-acceptance", reasonClass="unsupported-behaviour",
         text="**Acceptance criteria**\n- Alert when a mailbox gets a new forwarding rule to an external domain.\n- Include the rule name and destination."),
    dict(id="HO2-U-06", style="formal-spec", reasonClass="unsupported-field",
         text="SR-77. Raise an alert when successful logins for one account come from an IP address listed on the threat-intelligence Tor exit-node feed. Requires source_ip and the feed."),
    dict(id="HO2-U-07", style="sigma-like-yaml", reasonClass="unsupported-behaviour",
         text="detection:\n  event: account_lockout\n  count: 10\n  timeframe: 15m\n  group_by: domain_controller\n"),
    dict(id="HO2-U-08", style="email", reasonClass="unsupported-behaviour",
         text="Please alert us when a VPN session stays connected for more than 12 hours. The VPN concentrator log records session start and end."),
    dict(id="HO2-U-09", style="narrative", reasonClass="unsupported-behaviour",
         text="The intruder logged in, waited, and then changed the account's password before moving on. Alert when a successful login is followed by a password change on the same account within 10 minutes."),
    dict(id="HO2-U-10", style="checklist", reasonClass="unsupported-field",
         text="- [ ] Alert when the same account signs in from two different browsers within 10 minutes\n  - [ ] needs user_agent for every sign-in\n"),
    # ---- qualifiers
    dict(id="HO2-Q-01", style="email", reasonClass="qualifier",
         text="Alert when an account has 5 or more failed logins within 2 minutes and then logs in successfully, but only on weekends - weekday noise is handled elsewhere."),
    dict(id="HO2-Q-02", style="jira-acceptance", reasonClass="qualifier",
         text="**Acceptance criteria**\n1. Alert when a host fails against 6 or more distinct accounts within 10 minutes.\n2. Exclude hosts in the vulnerability-scanner allow-list."),
    dict(id="HO2-Q-03", style="chat-shorthand", reasonClass="qualifier",
         text="one account, successful logins from 3+ hosts inside 30 min, but only if one of the hosts is outside the corp network pls"),
    dict(id="HO2-Q-04", style="runbook-step", reasonClass="qualifier",
         text="Trigger: successful login for an MFA-required account with no MFA - limited to accounts in the finance group."),
    dict(id="HO2-Q-05", style="formal-spec", reasonClass="qualifier",
         text="SR-12. Alert on any successful login whose method differs from the account's expected method unless the source host is the jump server."),
    dict(id="HO2-Q-06", style="narrative", reasonClass="qualifier",
         text="We only care about VPN. Alert when a VPN login succeeds without MFA for an account that requires it; logins to internal systems are out of scope."),
    # ---- numeric / logical safety
    dict(id="HO2-N-01", style="email", reasonClass="ambiguous",
         text="Alert when 5 or more failed logins hit one account within 5 minutes, possibly 15, and then it succeeds - I'll confirm the window with the vendor."),
    dict(id="HO2-N-02", style="chat-shorthand", reasonClass="not-a-rule",
         text="no need to alert when 8 or more failed logins hit one account inside 2 minutes and then it succeeds - that's the password-manager retry bug"),
    dict(id="HO2-N-03", style="ticket", reasonClass="ambiguous",
         text="Alert when -2 or more distinct accounts fail from one host within 10 minutes."),
    dict(id="HO2-N-04", style="correction", reasonClass="contradictory",
         text="Alert when an account has 5 or more failed logins within 2 minutes and then succeeds.\n\n(Correction from the owner: the window is 10 minutes, not 2 minutes.)"),
    dict(id="HO2-N-05", style="formal-spec", reasonClass="ambiguous",
         text="SR-15. Alert when up to 5 failed logins for an account within 3 minutes are followed by a successful login."),
    dict(id="HO2-N-06", style="ticket", reasonClass="ambiguous",
         text="Alert when between 3 and 5 failed logins hit one account within 2 minutes and then it succeeds."),
    dict(id="HO2-N-07", style="chat-shorthand", reasonClass="ambiguous",
         text="alert when an account fails a couple of logins and then gets in within a few minutes"),
    dict(id="HO2-N-08", style="ticket", reasonClass="ambiguous",
         text="Alert when several accounts fail from the same host in a short time."),
    dict(id="HO2-N-09", style="ticket", reasonClass="ambiguous",
         text="Alert when one host fails against 4 or more distinct accounts within 30."),
    dict(id="HO2-N-10", style="email", reasonClass="contradictory",
         text="For the multi-host rule the ticket says both: alert on 2 or more distinct hosts within 2 hours, and elsewhere 2 or more distinct hosts within 20 minutes. Please just implement it."),
    dict(id="HO2-N-11", style="formal-spec", reasonClass="ambiguous",
         text="SR-19. Alert when exactly 5 failed logins for one account occur within 2 minutes and are followed by a successful login."),
    dict(id="HO2-N-12", style="narrative", reasonClass="ambiguous",
         text="Alert when an account averages more than 5 failed logins per hour over a day and then succeeds."),
    dict(id="HO2-N-13", style="hypothetical", reasonClass="not-a-rule",
         text="We discussed alerting on 5 or more failed logins for one account within 2 minutes followed by a success, and decided not to build it this quarter."),
    dict(id="HO2-N-14", style="contradictory-stakeholders", reasonClass="contradictory",
         text="Security asks for an alert on 5 or more failed logins for one account within 2 minutes then success. Compliance asks for 8 or more failed logins for one account within 2 minutes then success. Implement the detection."),
]
