package sentinelforge.compiler

import org.apache.spark.sql.{DataFrame, SparkSession}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types.{BooleanType, StringType}

/** Batch differential-test driver for `compiler/test/differential_property_test.py`
  * (item 13: an independent reference detector, plus property-based/differential
  * testing against it).
  *
  * Reads one JSON input describing, per behaviourId, a big UNIONED event list (and
  * a policy table) covering potentially thousands of scenarios generated by
  * Hypothesis on the Python side. Scenarios are never tagged with an explicit
  * "scenario id" column — each scenario is given its own globally-unique
  * account_id/source_host values (the same isolation trick
  * `scripts/datagen/incidents.py` already uses), so RuleCompiler's real,
  * unmodified `.select(...)` output can be run through ONCE per behaviour, at
  * full batch size, with zero changes to RuleCompiler.scala itself — this file
  * only reads input and writes output.
  *
  * Columns are extracted by NAME (`explode` + `.select("e.*")` + explicit casts), never by
  * position: Spark's JSON schema inference does not preserve source key order (typically
  * alphabetizes struct fields instead), so building a DataFrame positionally against a
  * hand-written StructType would silently scramble columns whenever the inferred order
  * disagrees with it — the exact hazard `StreamingCheck.scala` already documents and avoids
  * the same way.
  *
  * Usage: sbt "runMain sentinelforge.compiler.DifferentialCheck <in.json> <out.json>"
  */
object DifferentialCheck {

  def main(args: Array[String]): Unit = {
    require(args.length == 2, "usage: DifferentialCheck <in.json> <out.json>")
    val Array(inPath, outPath) = args

    val spark = SparkSession.builder().appName("sentinel-forge-differential-check").master("local[*]").getOrCreate()
    spark.sparkContext.setLogLevel("WARN")

    val input = spark.read.option("multiLine", "true").json(inPath)
    val behaviourIds = input.schema.fieldNames
    val repoRoot = new java.io.File(".").getCanonicalPath

    val perBehaviour = behaviourIds.map { behaviourId =>
      val spec = CompiledSpec.load(spark, s"$repoRoot/data/samples/ir/compiled/$behaviourId.compiled.json")

      val events = input.select(explode(col(s"`$behaviourId`.events")).as("e")).select("e.*")
        .select(
          col("event_id").cast(StringType), col("timestamp").cast(StringType),
          col("account_id").cast(StringType), col("event_type").cast(StringType),
          col("source_host").cast(StringType), col("auth_method").cast(StringType),
          col("mfa_used").cast(BooleanType),
          lit(null: String).as("source_ip"), lit(null: String).as("session_id"),
        )

      val policyOpt = if (spec.recipe == "PolicyCompare") {
        Some(input.select(explode(col(s"`$behaviourId`.policy")).as("p")).select("p.*")
          .select(
            col("account_id").cast(StringType),
            col("expected_auth_method").cast(StringType),
            col("mfa_required").cast(BooleanType),
          ))
      } else None

      val result = RuleCompiler.compile(spec, events, policyOpt)
      val rows = spec.recipe match {
        case "PolicyCompare" => result.select("groupKey", "triggeringEventId", "status").collect()
        case _               => result.withColumn("status", lit("alert")).select("groupKey", "triggeringEventId", "status").collect()
      }
      val alertsJson = rows.map { r =>
        s"""{"groupKey":${q(r.getString(0))},"triggeringEventId":${q(r.getString(1))},"status":${q(r.getString(2))}}"""
      }.mkString("[", ",", "]")
      s"""${q(behaviourId)}: $alertsJson"""
    }

    val pw = new java.io.PrintWriter(outPath, "UTF-8")
    try pw.write(perBehaviour.mkString("{", ",\n", "}")) finally pw.close()
    println(s"Wrote $outPath")

    spark.stop()
  }

  private def q(s: String): String =
    if (s == null) "null" else "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
